### ISSUE TITLE
Docker-compose env variables not passing through

### ISSUE THREAD

**Issue by remyderuysscher** [SynoCommunity/spksrc#3766]
### Setup
Docker
18.09.0-0505

DS918+
Intel
6.2.2-24922

docker-compose works but env variables are not passed through

it starts without environment variables and containers fail to start

1. 
```
    owntracks:
      image: owntracks/recorder:latest
      labels: [com.centurylinklabs.watchtower.enable=false]
      container_name: owntracks 
      ports:
        - "8181:8083"
      volumes:
        - /volume1/docker/owntracks:/store
      environment:
        - OTR_HOST='10.50.2.131' 
```

fails to start (address not available)

2. `docker run -d -p 8181:8083 -v /volume1/docker/owntracks:/store -e OTR_HOST=10.50.2.131 owntracks/recorder:latest`

works

Log:

` ot-recorder[7]: connecting to MQTT on localhost:1883 as clientID ot-recorder-38ab908bb883-7 without TLS`

Error: Address not available

See also discussion here:
https://www.reddit.com/r/synology/comments/cw75ck/dockercompose_dont_pass_anymore_env_to_docker/
