### ISSUE TITLE
dnscrypt-proxy Package Broken on DSM 7

### ISSUE THREAD

**Issue by Libre12** [SynoCommunity/spksrc#4744]
Error when trying to download:

"Invalid file format. Please contact the package developer"

### Setup
Package Name: dnscrypt-proxy
Package Version: 2.0.44-5

NAS Model: DS920+
NAS Architecture:  
DSM version: DSM 7.0-41890

### Expected behavior
It should install it

### Actual behavior
It downloads the package and immediately gives an error

### Steps to reproduce
1. Try to install it from the package manager

**Comment by hgy59** [comment]
Please regard the notes on the start page (README.rst) and #4524. dnscrypt-proxy is not updated for DSM7, and maybe it will never be installable on DSM7 as the package needs root privileges.

**Comment by publicarray** [comment]
@hgy59 just to add if/when it is ported it will be at a reduced feature set. Specifically I assume the port number has to be above 1024

**Comment by hgy59** [comment]
Yes, the following comment in service-setup.sh is the reason, it will be difficult to port dns-crypt-proxy to DSM7.
```
## I need root to bind to port 53 see `service_prestart()` below
```

**Comment by Libre12** [comment]
We can set the default port to 5353 and from the package DNS forward requests to it (127.0.0.1:5353).

Such setup would be even better because the DNS requests would be cached and hence served much faster than if they were handled directly to dnscrypt-proxy.

**Comment by publicarray** [comment]
@Libre12 I'm working on something [here](https://github.com/publicarray/spksrc/tree/dnscrypt-proxy-dsm7) yes the default port will be different (I've used 10053 as 5353 is already assigned and used for Multicast DNS e.g. bonjour uses it), and my plan at the moment to remove the GUI to edit the config file and instead migrate it to a separate package: [synoedit](https://github.com/publicarray/synoedit).

FYI dnscrypt-proxy already caches requests and IMHO is better at doing it. But you can turn it off with ` cache = false` 

the full option list (from a newer version so some don't apply yet)
```toml
 ###########################
#        DNS cache        #
###########################

## Enable a DNS cache to reduce latency and outgoing traffic

cache = true


## Cache size

cache_size = 4096


## Minimum TTL for cached entries

cache_min_ttl = 2400


## Maximum TTL for cached entries

cache_max_ttl = 86400


## Minimum TTL for negatively cached entries

cache_neg_min_ttl = 60


## Maximum TTL for negatively cached entries

cache_neg_max_ttl = 600
```
